---
apiVersion: apps/v1
kind: Deployment
metadata:
	name: ide.user1course1
  namespace: ide
  labels:
		app: ide.user1course1
spec:
  replicas: 1
  selector:
    matchLabels:
			app: ide.user1course1
  template:
    metadata:
      labels:
				app: ide.user1course1
    spec:
      containers:
				- name: ide.dXNlcjFjb3Vyc2Ux
					image: milkymilky0116/ide:user1course1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 250m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20