apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-server
  namespace: container-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container-server
  template:
    metadata:
      labels:
        app: container-server
    spec:
      containers:
        - name: container-server
          image: milkymilky0116/flake-ide-container-server:ad3c239
          ports:
            - containerPort: 50051
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: container-server-secret
                  key: docker_username
            - name: DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: container-server-secret
                  key: docker_username
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
