apiVersion: v1
kind: Secret
metadata:
  name: container-server-secret
  namespace: container-server
type: Opaque
data:
  docker_username: bWlsa3ltaWxreTAxMTY=
  docker_credentials: ZGNrcl9wYXRfMXpPNTdHelU2amxfWVQ4SjVETmZfS05faXdJ
