apiVersion: v1
kind: Service
metadata:
  name: container-server
  namespace: container-server
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31000
  selector:
    app: container-server
