apiVersion: v1
kind: Service
metadata:
  name: container-server
  namespace: container-server
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 31000
  selector:
    app: container-server
