apiVersion: v1
kind: Service
metadata:
  name: flakeide-fe
  namespace: flakeide-fe
spec:
  type: NodePort
  selector:
    app: flakeide-fe
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
