apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-route
  namespace: jenkins
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`jenkins.flakeide.com`)
      kind: Rule
      services:
        - name: jenkins
          port: 8080
  tls:
    certResolver: myresolver
