deployment:
  enabled: true
  podAnnotations:
    traefik.enable: "true"

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
  - "--api.insecure=false"
  - "--certificatesresolvers.letsencryptresolver.acme.email={{ .Values.email }}"
  - "--certificatesresolvers.letsencryptresolver.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencryptresolver.acme.tlschallenge=true"

ports:
  web:
    port: 80
    expose: true
  websecure:
    port: 443
    expose: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

env:
  - name: EMAIL
    valueFrom:
      secretKeyRef:
        name: traefik-secrets
        key: email

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    routes:
      - match: Host(`traefik.{{ .Values.domainname }}`)
        kind: Rule
        middlewares:
          - admin

middlewares:
  admin:
    basicAuth:
      usersSecret: "traefik-secrets"

secret:
  email: ${EMAIL}
  basicAuth:
    HTTP_BASIC_USER: ${HTTP_BASIC_USER}
    HTTP_BASIC_PWD: ${HTTP_BASIC_PWD}
