# jenkins-values.yaml
controller:
  image: "jenkins/jenkins:lts" # Jenkins 이미지
  tag: "lts"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  service:
    type: ClusterIP
    port: 5000
persistence:
  enabled: true
  size: "10Gi"
  storageClass: "standard" # 필요한 경우, 스토리지 클래스 이름으로 변경
