controller:
  image: "jenkins/jenkins:lts" # Jenkins Docker Hub 이미지
  installPlugins:
    - kubernetes:1.30.0
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.7.1
  serviceType: LoadBalancer
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
