apiVersion: apps/v1
kind: Deployment
metadata:
  name: flakeide-be
  namespace: flakeide-be
  labels:
    app: flakeide-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flakeide-be
  template:
    metadata:
      labels:
        app: flakeide-be
    spec:
      containers:
        - name: flakeide-be
          image: milkymilky0116/flake-ide-be:ecb15e5
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: db_name

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 120
