apiVersion: v1
kind: Service
metadata:
  name: flakeide-be
  namespace: flakeide-be
spec:
  type: NodePort
  selector:
    app: flakeide-be
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32001
